<script>
    import { onMount     } from "svelte";

    let isOpen = $state(false);
    let showPages = $state(false);

    let main = null;
    let bookOpened = null;
    let shine = null;

    function animateBook() {
        if (isOpen) {
            // Hide pages first, then animate book closed.
            showPages = false;
            isOpen = false;
            return;
        }

        isOpen = true;
    }

    async function handleBookTransitionEnd(event) {
        if (event.propertyName !== "transform") return;
        if (isOpen) showPages = true;
    }

    /** @param {MouseEvent} event */
    function handleDocumentClick(event) {
        if (!showPages || !bookOpened) return;
        if (!(event.target instanceof Node)) return;

        // Close when the click happens outside the opened book panel.
        if (!bookOpened.contains(event.target)) {
            showPages = false;
            isOpen = false;
        }
    }

    onMount(() => {
        document.addEventListener("click", handleDocumentClick);

        return () => {
            document.removeEventListener("click", handleDocumentClick);
        };
    });

    const faqItems = [
        {
            q: "What is Paradox?",
            a: "Paradox is a You ship We ship (YSWS) where you submit cool story-related projects in exchange for prizes such as art grants, video game grants, cool merch, or a ticket to Fable!\n",
        },
        {
            q: "What can I submit?",
            a: "You can submit media in any form that contains a story, this includes video games, visual novels, hardware projects, etc.\n",
        },
        {
            q: "Do I need to have any prior experience?",
            a: "Nope! Paradox is completely beginner friendly and we welcome people with any amount of experience to join and make cool projects!\n",
        },
        {
            q: "What is fraud?",
            a: "Fraud is when you deliberately try to misrepresent your project in a different manner, this includes (but not limited to):\n" +
                "\n" +
                "* inflating your hours on hackatime to receive a higher payout\n" +
                "* submitting a template/guide with no unique changes made to it\n" +
                "* submitting entirely AI generated or copied code and claiming it as your own\n" +
                "\n" +
                "The consequences of committing fraud. includes being banned from paradox, and in sever cases, being banned from Hackatime, hence being banned from all Hack Club events.\n",
        },
        {
            q: "Can I work with others?",
            a: "Yes you can! We encourage you to work with others on cool projects, just make sure that you individually log your hours on Hackatime and submit your projects separately.\n",
        },
        {
            q: "Can I use AI?",
            a: "AI is not allowed in any capacity for creating any music or art for your project. AI can be used for help outside of that, such as for writing code, or research, however only up to 30% of your code can be generated by AI. If AI slop is submitted it will be automatically rejected, and it may lead to being banned from Paradox.\n",
        },
    ]

    let selected = $state(0);
</script>

<main
    class="main w-full min-h-screen relative overflow-hidden"
    bind:this={main}
>

    <div class="absolute top-0 left-0 p-4 sm:p-6">
        <button onclick={() => (window.location.href = "/")}>
            <img
                    src="/images/faq/faq-btn.png"
                    class="min-w-52 w-64 max-w-[20vw] transition-all duration-300 ease-in-out hover:opacity-60 cursor-pointer"
                    alt="Home Button"
            />
        </button>
    </div>

    <button class="absolute bottom-0 left-1/2 -translate-x-1/2 cursor-auto" onclick={animateBook}>
        <img
                src="/images/faq/faq-book.png"
                class="min-w-[20rem] w-[50rem] max-w-[45vw] transition-all duration-700 ease-in-out hover:opacity-80 cursor-pointer"
                class:openBook={isOpen}
                ontransitionend={handleBookTransitionEnd}
                alt="FAQ Playbook"
        />
    </button>

    <div
        class="absolute bottom-0 left-1/2 -translate-x-1/2 flex-row"
        class:flex={showPages}
        class:hidden={!showPages}
        bind:this={bookOpened}
    >
        <div
            class="bg-[#EDEAE1] min-h-[20rem] h-[50rem] min-w-[20rem] w-[38rem] max-w[42rem] border-r-2 border-black rounded-lg p-10"
        >
            <div class="h-4 w-[100%] bg-black"></div>
            <div class="h-1 w-[100%] bg-black mt-2"></div>
            <h1 style="font-family: 'Bethany, serif'" class="text-8xl">FAQ</h1>
            <div class="h-1 w-[30%] bg-black mt-6"></div>
            {#each faqItems as item, i}
                <button
                        class="text-4xl mt-6 text-left hover:underline hover:font-bold"
                        class:font-bold={selected === i}
                        onclick={() => (selected = i)}
                        style="font-family: 'Bethany', serif"
                >
                    {item.q}
                </button>
            {/each}
            <div class="h-1 w-[30%] bg-black mt-6"></div>
            <div class="flex flex-row items-center gap-3 mt-16">
                <img
                    src="images/faq/faq-logo.png"
                    alt="Paradox Logo"
                />
                <img
                        src="images/faq/faq-star.png"
                        alt="Star"
                        class="object-contain"
                />
                <h1
                    class="text-4xl"
                    style="font-family: 'Bethany', serif"
                >
                    Hack Club 2026
                </h1>
            </div>
        </div>
        <div class="bg-[#EDEAE1] min-h-[20rem] h-[50rem] min-w-[20rem] w-[38rem] max-w[42rem] rounded-lg p-10 flex flex-col">
            <div class="flex flex-row items-center">
                <div class="flex flex-col items-center w-full">
                    <div class="h-4 w-[75%] bg-black"></div>
                    <div class="h-1 w-[75%] bg-black mt-2"></div>
                </div>
                <h1
                        class="text-6xl"
                        style="font-family: 'Bethany', serif"
                >
                    ANSWER
                </h1>
                <div class="flex flex-col items-center w-full">
                    <div class="h-4 w-[75%] bg-black"></div>
                    <div class="h-1 w-[75%] bg-black mt-2"></div>
                </div>
            </div>

            <div class="h-1 w-[100%] bg-black mt-6"></div>

            <div class="flex-1 overflow-y-auto">
                <h1
                    class="text-2xl text-center mt-14"
                    style="font-family: 'Bethany', serif">
                    {faqItems[selected].a}
                </h1>
            </div>

            <footer class="flex flex-col items-end justify-end mt-auto">
                <div class="h-1 w-[100%] bg-black"></div>

                <div class="flex flex-row items-center w-full mt-4">
                    <div class="flex-col flex w-full justify-between">
                        <p
                                class="text-lg"
                                style="font-family: 'Bethany', serif"
                        >
                            produced by
                        </p>
                        <a
                                href="https://hackclub.com"
                                class="text-3xl"
                                style="font-family: 'Bethany', serif"
                        >
                            Hack Club
                        </a>
                    </div>
                    <div class="flex-col w-full flex items-end justify-end">
                        <p
                                class="text-lg"
                                style="font-family: 'Bethany', serif"
                        >
                            directed by teens
                        </p>
                        <div class="flex flex-row">
                            <p
                                    class="text-3xl"
                                    style="font-family: 'Bethany', serif"
                            >
                                for teens
                            </p>
                            <img
                                    src="/images/faq/faq-star.png"
                                    class="ml-2"
                                    alt="Star"
                            />
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

</main>


<style>
    .main {
        background-image: url("/images/faq/faq-bg.png");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }

    .openBook  {
        transform-origin: center bottom;
        transform: translateY(10%);
        cursor: auto;
    }
</style>