class FaqController < ApplicationController
  def index
    @faq_items = [
      {
        q: "What is Paradox?",
        a: "Paradox is a You ship We ship (YSWS) where you submit cool story-related projects in exchange for prizes such as art grants, video game grants, cool merch, or a ticket to Fable!"
      },
      {
        q: "What can I submit?",
        a: "You can submit media in any form that contains a story, this includes video games, visual novels, hardware projects, etc."
      },
      {
        q: "Do I need to have any prior experience?",
        a: "Nope! Paradox is completely beginner friendly and we welcome people with any amount of experience to join and make cool projects!"
      },
      {
        q: "What is fraud?",
        a: "Fraud is when you deliberately try to misrepresent your project in a different manner, this includes (but not limited to):\n\n* inflating your hours on hackatime to receive a higher payout\n* submitting a template/guide with no unique changes made to it\n* submitting entirely AI generated or copied code and claiming it as your own\n\nThe consequences of committing fraud includes being banned from paradox, and in severe cases, being banned from Hackatime, hence being banned from all Hack Club events."
      },
      {
        q: "Can I work with others?",
        a: "Yes you can! We encourage you to work with others on cool projects, just make sure that you individually log your hours on Hackatime and submit your projects separately."
      },
      {
        q: "Can I use AI?",
        a: "AI is not allowed in any capacity for creating any music or art for your project. AI can be used for help outside of that, such as for writing code, or research, however only up to 30% of your code can be generated by AI. If AI slop is submitted it will be automatically rejected, and it may lead to being banned from Paradox."
      }
    ]
  end
end
